---
services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server
    hostname: openssh-server #optional
    environment:
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=password
      - USER_NAME=user
      - PUBLIC_KEY_FILE=/data/test.key.pub
    ports:
      - "2222:2222"
    volumes:
      - ./src/test/resources/data/test.key.pub:/data/test.key.pub
    restart: unless-stopped